### ISSUE TITLE
Postgres not configured for UTF-8

### ISSUE THREAD

**Issue by pivotal-shipio** [pivotal-sprout/sprout-wrap#60]
With "encoding: UTF-8" in our schema.rb file we cannot create a database out of the box. We got a bunch of errors related to default encodings. The solution was to uninstall postgres and its data. From initdb we had to recreate the db with "initdb -E utf8". 

-Sam on behalf of Ship.io

**Comment by hiremaga** [comment]
Sorry about the slow response to this issue @pivotal-shipio.

I'm going to close this since it affects the [sprout-postgresql](https://github.com/pivotal-sprout/sprout-postgresql) cookbook. If this is still a problem, could you please submit an issue or pull request describing how that cookbook should be changed to address this?

Also, if this is a problem with the homebrew formula for postgres, then please submit this issue/pr to [that repo](github.com/homebrew/homebrew) instead.
